
-- Table: USER
CREATE TABLE USER ( 
    USER_ID       INTEGER PRIMARY KEY ASC AUTOINCREMENT,
    USER_USERNAME VARCHAR,
    USER_PASSWORD VARCHAR 
);

INSERT INTO [USER] ([USER_ID], [USER_USERNAME], [USER_PASSWORD]) VALUES (1, '¿Ó±Û', 123);

-- Table: PART
CREATE TABLE PART ( 
    PART_ID        INTEGER            PRIMARY KEY ASC AUTOINCREMENT,
    PART_NAME      VARCHAR( 0, 100 ),
    PART_REMARK    VARCHAR( 0, 100 ),
    PART_NUM       INTEGER,
    REMARK         BLOB,
    PART_NUM_LIMIT INTEGER 
);

INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (5, 'EEE111', 'EEE-A–Õ∫≈111', 28, 1111, 40);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (6, 'RRR222', 'RRR-B–Õ∫≈111', 29110, 'rrr111', 30111);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (9, 'III', '', 10, '', 50);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (10, 'OOO', '', 0, '', 30);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (11, 'PPP', '', 40, '', 30);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (12, 'PPPT', null, 50, null, null);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (13, 'SER', null, 60, null, null);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (14, 'FTK', null, null, null, null);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (15, 'SSA', null, null, null, null);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (32, 6, 6, 6, 6, 6);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (33, 1, 1, 1, 1, 1);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (34, 1, 2, 3, 4, 5);
INSERT INTO [PART] ([PART_ID], [PART_NAME], [PART_REMARK], [PART_NUM], [REMARK], [PART_NUM_LIMIT]) VALUES (35, 'AAA-X-1', 'sd', 12, 3, 11);
